# Generated by Django 5.0.4 on 2024-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_post_total_likes_post_socialapp_p_total_l_2187a6_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('subject', models.CharField(choices=[('C', 'criticism'), ('P', 'proposal'), ('R', ' report')], max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
